---
title: "Lista06_FernandaVincenzo"
author: "Fernanda Di Vincenzo 280867"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)

conn <- dbConnect(RSQLite::SQLite(), "datasets/me315.sqlite")
```

## TABELA PRESERVE

```{sql connection=conn}
SELECT * FROM PRESERVE
```

1 - Para cada estado mencionado na tabela PRESERVE, exiba o valor de ACRES da menor área de preservação natural localizada nesse estado.
```{sql connection=conn}
SELECT STATE, MIN(ACRES) AS MENOR_ACRE FROM PRESERVE
GROUP BY STATE

```
2 - Não considere nenhuma área de preservação natural que tenha mais de 10.000 acres. Para cada estado mencionado na tabela PRESERVE, exiba o valor de ACRES da maior área de preservação natural localizada nesse estado.
```{sql connection=conn}
SELECT STATE, MAX(ACRES) AS MAIOR_ACRE FROM PRESERVE
WHERE ACRES <= 10000
GROUP BY STATE


```
3 - Na Tabela resultante anterior, ordene os resultados pelos valores máximos, em ordem decrescente.
```{sql connection=conn}
SELECT STATE, MAX(ACRES) AS MAIOR_ACRE FROM PRESERVE
WHERE ACRES <= 10000
GROUP BY STATE
ORDER BY MAIOR_ACRE DESC


```
4 - Exiba o tamanho, em acres, da maior área de preservação natural de cada estado, desde que esse valor seja inferior a 25.000 acres.
```{sql connection=conn}
SELECT STATE, MAX(ACRES) AS MAIOR_ACRE FROM PRESERVE
GROUP BY STATE
HAVING MAIOR_ACRE < 25000


```
5 - Para cada estado mencionado na tabela PRESERVE, exiba o número de acres da menor área de preservação do estado, desde que esse número seja inferior a 100 acres.
```{sql connection=conn}
SELECT STATE, MIN(ACRES) AS MENOR_ACRE FROM PRESERVE
GROUP BY STATE
HAVING MENOR_ACRE < 100


```
6 - Considere apenas as áreas de preservação natural com mais de 1.000 acres. Para cada estado, exiba o nome e o tamanho (em acres) da maior área de preservação natural desse estado, desde que esse valor seja inferior a 25.000 acres.
```{sql connection=conn}
SELECT PNAME, MAX(ACRES) AS MAIOR_ACRE FROM PRESERVE
WHERE ACRES > 1000
GROUP BY STATE
HAVING MAIOR_ACRE < 25000

```
7 - Exiba o estado e o tamanho total, em acres, das áreas de preservação localizadas nesse estado, desde que o tamanho total seja maior ou igual a 10.000 acres e menor ou igual a 50.000 acres.
```{sql connection=conn}
SELECT STATE, SUM(ACRES) AS TOTAL_ACRES FROM PRESERVE
GROUP BY STATE
HAVING TOTAL_ACRES BETWEEN 10000 AND 50000



```
8 - Determine a quantidade média de acres das áreas de preservação para cada estado e, em seguida, exiba a maior dessas médias.
```{sql connection=conn}
SELECT STATE, AVG(ACRES) AS MEDIA FROM PRESERVE
GROUP BY STATE
ORDER BY MEDIA DESC
LIMIT 1

```

## TABELA EMPLOYEE
```{sql connection=conn}
SELECT * FROM EMPLOYEE
```
9 - Para todos os valores de DNO dos departamentos encontrados na tabela EMPLOYEE, exiba o valor de DNO, seguido pelo salário médio daquele departamento.
```{sql connection=conn}
SELECT DNO, AVG(SALARY) FROM EMPLOYEE
GROUP BY DNO

```
10 - Para todos os valores de DNO dos departamentos encontrados na tabela EMPLOYEE, exiba o valor de DNO, seguido pela soma, pelo máximo e pelo mínimo dos salários daquele departamento.
```{sql connection=conn}
SELECT DNO, SUM(SALARY), MIN(SALARY), MAX(SALARY) FROM EMPLOYEE
GROUP BY DNO

```
11 - Considere todos os departamentos, exceto o Departamento 40. Para esses departamentos, exiba o valor de DNO, seguido pelo número de funcionários que trabalham em cada departamento.
```{sql connection=conn}
SELECT DNO, COUNT(*) FROM EMPLOYEE
WHERE DNO  <> 40
GROUP BY DNO

```
12 - Para cada departamento, determine o número total de funcionários que trabalham naquele departamento. Suponha que a coluna SALARY contenha dados confidenciais e que alguém possa deduzir essas informações confidenciais examinando o total dos salários de cada departamento. Portanto, decida exibir apenas os departamentos nos quais o número de funcionários seja superior a dois.
```{sql connection=conn}
SELECT DNO, COUNT(*) AS TOTAL FROM EMPLOYEE
GROUP BY DNO
HAVING TOTAL > 2

```
13 - Escreva uma solução que possa ser utilizada para reproduzir a seguinte tabela.
STATE	SUM (ACRES)
AZ	51360
MA	1760
MT	16931
Total	70051
```{sql connection=conn}
SELECT STATE, SUM(ACRES) FROM PRESERVE
GROUP BY STATE
UNION ALL
SELECT 'TOTAL', SUM(ACRES) FROM PRESERVE
```