---
title: "Lab04_FernandaVincenzo"
author: "Fernanda Di Vincenzo 280867"
format: pdf
editor: source
---

## Q1:

```{r}

library(readxl)
library(tidyverse)
```

## Q2:
```{r}
fname <- file.path("datasets/wdiexcel.xlsx")
file.exists(fname)
```
## Q3:
```{r}
countries <- read_excel(fname, sheet = "Country")
```

## Q4:
```{r}
countries <- countries |>
  filter(`Short Name` %in% c(
    "Brazil",
    "China",
    "Spain",
    "France",
    "Norway"
  ))
```

## Q5:
```{r}
WDI <- read_excel(fname, sheet = "Data")
```

## Q6:
```{r}
WDI <- WDI |>
  select(
   'Country Code',
   'Indicator Code',
   '1960':'2018'
  )
```

##Q7:

Não estão no formato tidy, pois todos os anos estão como colunas próprias.
```{r}
WDI <- WDI |>
  pivot_longer(
    cols = `1960`:`2018`,
    names_to = "YEAR",
    values_to = "value"
  )
```

##Q8:
```{r}

is.integer(WDI$YEAR)

WDI <- WDI |>
  mutate(YEAR = as.integer(YEAR))


is.integer(WDI$YEAR)
```
##Q9:
```{r}
WDI <- WDI |>
  semi_join(
    countries,
    by = "Country Code"
  ) |>
  filter(`Indicator Code` == "SP.DYN.CBRT.IN") |>
  left_join(
    countries |>
      select(`Country Code`, `Short Name`),
    by = "Country Code"
  ) |>
  select(
    `Country Code`,
    `Short Name`,
    YEAR,
    `SP.DYN.CBRT.IN` = value
  )
```

##Q10:
```{r}
WDI <- WDI |>
  arrange(`Short Name`, YEAR)
```

##Q11:
```{r}
ggplot(
  WDI,
  aes(
    x = YEAR,
    y = `SP.DYN.CBRT.IN`,
    color = `Short Name`,
    group = `Short Name`
  )
) +
  geom_line(na.rm = TRUE) +
  labs(
    x = "Ano",
    y = "Taxa bruta de natalidade",
    color = "País"
  ) +
  theme_minimal()
```

```{r}

Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

